### ISSUE TITLE
Clean up meta.

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/Gears#19]
At the moment, the meta module is really messy. Everything is lodged into `alias.hpp` or `meta.hpp` with little to no in between. 

Possible solutions that are open to consideration:
- Make every meta function into its own header, e.g. `if.hpp`, `and.hpp`, etc.
- Better grouping of meta functions.
- Better documentation for the meta module.

**Comment by ThePhD** [comment]
conditionals.hpp
-- if, and, or, etc.
type_strip.hpp
-- unqualified, unwrap, decay, etc.

You can still take this approach too if you put each in its own header, and then just group the `#include`'s together in a grouping header.
